<?php

namespace Container1jzXs0H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSignUpFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\SignUpFormType' shared autowired service.
     *
     * @return \App\Form\SignUpFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/SignUpFormType.php';

        return $container->privates['App\\Form\\SignUpFormType'] = new \App\Form\SignUpFormType();
    }
}
