<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1jzXs0H\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1jzXs0H/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1jzXs0H.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1jzXs0H\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1jzXs0H\App_KernelDevDebugContainer([
    'container.build_hash' => '1jzXs0H',
    'container.build_id' => 'a55839dd',
    'container.build_time' => 1687298940,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1jzXs0H');
